# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: Priorr

channels:
  - conda-forge
  - bioconda

dependencies:
  - conda-forge::r-base=3.6.3 
  - conda-forge::shiny
  - conda-forge::DT    #  for data tables
  - conda-forge::dplyr
  - conda-forge::shinyWidgets
  - conda-forge::lazyeval
  - conda-forge::shinydashboard
  - conda-forge::shinydashboardPlus=0.7.5
  - conda-forge::data.table
  - conda-forge::shinyalert
  - conda-forge::filesstrings
  - conda-forge::shinyBS
  - conda-forge::shinyjs
  - conda-forge::optparse